repos:
  - repo: local
    hooks:
      - id: ruff-import-sort
        name: ruff import sort
        entry: uv run ruff check --select I --fix .
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format .
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace